

'use client';

import { motion, useInView } from 'framer-motion';
import { useRef, useState } from 'react';
import { BarChart3, Bell, Brain, Lock, Map, Palette, Target, Sparkles } from 'lucide-react';

const features = [
  {
    icon: Lock,
    title: 'Secure Authentication',
    description: 'JWT-based login with email verification and refresh tokens',
    colorClass: 'feature-gradient-blue',
  },
  {
    icon: Target,
    title: 'Smart Skill Tracking',
    description: 'CRUD operations, categorization, and real-time progress updates',
    colorClass: 'feature-gradient-rose',
  },
  {
    icon: BarChart3,
    title: 'Time-Based Logging',
    description: 'Daily progress logs with time tracking and detailed notes',
    colorClass: 'feature-gradient-amber',
  },
  {
    icon: Map,
    title: 'Resource Library',
    description: 'Manage learning materials linked to skills with usage tracking',
    colorClass: 'feature-gradient-emerald',
  },
  {
    icon: Brain,
    title: 'AI-Powered Summaries',
    description: 'Weekly insights generated by Gemini API with personalized recommendations',
    colorClass: 'feature-gradient-violet',
  },
  {
    icon: BarChart3,
    title: 'Visual Analytics',
    description: 'Interactive charts, streak tracking, and gamification elements',
    colorClass: 'feature-gradient-indigo',
  },
  {
    icon: Bell,
    title: 'Smart Notifications',
    description: 'Automated email summaries and reminders to keep you on track',
    colorClass: 'feature-gradient-red',
  },
  {
    icon: Palette,
    title: 'Modern UI/UX',
    description: 'Responsive design with animations and accessible components',
    colorClass: 'feature-gradient-primary',
  },
];

export default function FeaturesSection() {
  const ref = useRef(null);
  const isInView = useInView(ref, { once: true, margin: '-100px' });
  const [hoveredIndex, setHoveredIndex] = useState<number | null>(null);

  const containerVariants = {
    hidden: { opacity: 0 },
    visible: {
      opacity: 1,
      transition: {
        staggerChildren: 0.08,
        delayChildren: 0.2,
      },
    },
  };

  const itemVariants = {
    hidden: { opacity: 0, y: 40, scale: 0.9, rotateX: -20 },
    visible: {
      opacity: 1,
      y: 0,
      scale: 1,
      rotateX: 0,
      transition: {
        duration: 0.6,
        ease: [0.4, 0, 0.2, 1] as const,
      },
    },
  };

  const headerVariants = {
    hidden: { opacity: 0, y: 30 },
    visible: {
      opacity: 1,
      y: 0,
      transition: {
        duration: 0.6,
        ease: [0.4, 0, 0.2, 1] as const,
      },
    },
  };

  const badgeVariants = {
    hidden: { opacity: 0, scale: 0.8 },
    visible: {
      opacity: 1,
      scale: 1,
      transition: {
        duration: 0.5,
        ease: [0.34, 1.56, 0.64, 1] as const,
      },
    },
  };

  return (
    <section id="features" ref={ref} className="features-section relative overflow-hidden">
      {/* Animated Background Blobs */}
      <div className="features-bg-pattern absolute inset-0 pointer-events-none">
        <motion.div
          className="features-blob-primary"
          animate={{
            scale: [1, 1.2, 1],
            x: [0, 30, 0],
            y: [0, -20, 0],
          }}
          transition={{
            duration: 20,
            repeat: Infinity,
            ease: 'easeInOut',
          }}
        />
        <motion.div
          className="features-blob-info"
          animate={{
            scale: [1.2, 1, 1.2],
            x: [0, -40, 0],
            y: [0, 30, 0],
          }}
          transition={{
            duration: 25,
            repeat: Infinity,
            ease: 'easeInOut',
          }}
        />
      </div>

      <div className="container mx-auto px-4 sm:px-6 lg:px-8 relative z-10 max-w-7xl">
        {/* Section Header */}
        <motion.div
          variants={headerVariants}
          initial="hidden"
          animate={isInView ? 'visible' : 'hidden'}
          className="text-center mb-16"
        >
          <motion.div
            variants={badgeVariants}
            className="features-badge inline-flex items-center gap-2 px-4 py-2 rounded-full border mb-6"
          >
            <motion.div
              animate={
                isInView
                  ? {
                      rotate: [0, 360],
                      scale: [1, 1.2, 1],
                    }
                  : {}
              }
              transition={{
                duration: 2,
                delay: 0.5,
                ease: 'easeInOut',
              }}
            >
              <Sparkles className="features-badge-icon h-4 w-4" />
            </motion.div>
            <span className="features-badge-text text-sm font-medium">Features</span>
          </motion.div>

          <motion.h2
            initial={{ opacity: 0, y: 20 }}
            animate={isInView ? { opacity: 1, y: 0 } : {}}
            transition={{ duration: 0.6, delay: 0.2 }}
            className="features-title font-bold text-4xl sm:text-5xl lg:text-6xl mb-4"
          >
            Everything You Need to{' '}
            <motion.span
              className="features-gradient inline-block"
              animate={
                isInView
                  ? {
                      backgroundPosition: ['0% 50%', '100% 50%', '0% 50%'],
                    }
                  : {}
              }
              transition={{
                duration: 5,
                repeat: Infinity,
                ease: 'linear',
              }}
              style={{
                backgroundSize: '200% 200%',
              }}
            >
              Grow
            </motion.span>
          </motion.h2>

          <motion.p
            initial={{ opacity: 0, y: 20 }}
            animate={isInView ? { opacity: 1, y: 0 } : {}}
            transition={{ duration: 0.6, delay: 0.3 }}
            className="features-description text-lg sm:text-xl max-w-2xl mx-auto"
          >
            A comprehensive platform that transforms how you track, measure, and achieve your skill
            development goals through intelligent progress tracking.
          </motion.p>
        </motion.div>

        {/* Features Grid */}
        <motion.div
          variants={containerVariants}
          initial="hidden"
          animate={isInView ? 'visible' : 'hidden'}
          className="grid sm:grid-cols-2 lg:grid-cols-4 gap-6"
        >
          {features.map((feature, index) => (
            <motion.div
              key={feature.title}
              variants={itemVariants}
              onHoverStart={() => setHoveredIndex(index)}
              onHoverEnd={() => setHoveredIndex(null)}
              whileHover={{
                y: -12,
                scale: 1.03,
                transition: {
                  duration: 0.3,
                  ease: 'easeOut',
                },
              }}
              className="feature-card-wrapper group"
            >
              {/* Gradient Border with Animation */}
              <motion.div
                className={`feature-card-border ${feature.colorClass}`}
                initial={{ opacity: 0 }}
                animate={{
                  opacity: hoveredIndex === index ? 1 : 0,
                }}
                transition={{ duration: 0.3 }}
              />

              <div className="feature-card relative">
                {/* Icon with Advanced Animations */}
                <motion.div
                  className={`feature-icon-wrapper ${feature.colorClass}`}
                  animate={
                    hoveredIndex === index
                      ? {
                          scale: 1.15,
                          rotate: 8,
                          y: -4,
                        }
                      : {
                          scale: 1,
                          rotate: 0,
                          y: 0,
                        }
                  }
                  transition={{
                    type: 'spring',
                    stiffness: 400,
                    damping: 15,
                  }}
                >
                  <motion.div
                    animate={
                      isInView
                        ? {
                            rotate: [0, -8, 8, -8, 0],
                          }
                        : {}
                    }
                    transition={{
                      duration: 2,
                      delay: 0.8 + index * 0.1,
                      ease: 'easeInOut',
                    }}
                  >
                    <feature.icon className="feature-icon h-6 w-6" />
                  </motion.div>
                </motion.div>

                {/* Title with Character Animation */}
                <motion.h3 className="feature-card-title text-lg font-semibold mb-2">
                  {feature.title.split('').map((char, i) => (
                    <motion.span
                      key={i}
                      initial={{ opacity: 0, y: 10 }}
                      animate={isInView ? { opacity: 1, y: 0 } : {}}
                      transition={{
                        duration: 0.3,
                        delay: 0.6 + index * 0.08 + i * 0.02,
                      }}
                      style={{ display: 'inline-block' }}
                    >
                      {char === ' ' ? '\u00A0' : char}
                    </motion.span>
                  ))}
                </motion.h3>

                {/* Description with Fade In */}
                <motion.p
                  initial={{ opacity: 0 }}
                  animate={isInView ? { opacity: 1 } : {}}
                  transition={{
                    duration: 0.5,
                    delay: 0.8 + index * 0.08,
                  }}
                  className="feature-card-description text-sm leading-relaxed"
                >
                  {feature.description}
                </motion.p>

                {/* Hover Glow Effect */}
                <motion.div
                  className="absolute inset-0 rounded-xl pointer-events-none"
                  style={{
                    background: `radial-gradient(circle at center, ${
                      hoveredIndex === index ? 'hsl(var(--primary) / 0.05)' : 'transparent'
                    }, transparent 70%)`,
                  }}
                  animate={{
                    opacity: hoveredIndex === index ? 1 : 0,
                  }}
                  transition={{ duration: 0.3 }}
                />
              </div>
            </motion.div>
          ))}
        </motion.div>

        {/* Floating Particles Effect */}
        {isInView && (
          <>
            {[...Array(6)].map((_, i) => (
              <motion.div
                key={i}
                className="absolute w-2 h-2 rounded-full bg-primary/20"
                style={{
                  left: `${20 + i * 15}%`,
                  top: `${30 + (i % 3) * 20}%`,
                }}
                animate={{
                  y: [0, -30, 0],
                  opacity: [0, 0.6, 0],
                  scale: [0, 1, 0],
                }}
                transition={{
                  duration: 3 + i * 0.5,
                  repeat: Infinity,
                  delay: i * 0.5,
                  ease: 'easeInOut',
                }}
              />
            ))}
          </>
        )}
      </div>
    </section>
  );
}